### ISSUE TITLE
Licensing of this fork

### ISSUE THREAD

**Issue by phoe** [Lisp-Stat/array-operations#1]
MIT license states:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

0b9c45b9fd0b43ec0f0137d5713560d720ecaf88 removes the "copyright notice" that the above portion of MIT license talks about. f63ae44eee921266006176774a5cb8b797196ce4 removes the MIT license text altogether, which means that the "permission notice" is not included either.

Isn't that a full-on license breach?

**Comment by snunez1** [comment]
I'm not a lawyer, but in either case I'd be fine with it under MIT.  My time is short at the moment with a new job and I'd be grateful for a pull request.
